config/routes.rb
Rails.application.routes.draw do
 
  get 'image_elements/index'
  get 'image_elements/new'
  get 'image_elements/auras'
  get 'image_elements/details'
  get 'spotify/index'
  get 'pages/index'
  post 'messages', to: 'pages#create'
  get 'spotify/index'
  get 'oracles', to: 'oracles#index'
  get 'enemies', to: 'grudges#create'
  get 'youtube/index'
  get 'vibes/vibemeter'
  
 

 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  
 

  
  resources :vibes 
  

  resources :image_elements
  resources :oracles
  resource :messages
  resources :pages
  resources :students, only: [:index, :new, :create]
 
  resources :students do
    resources :lessons, shallow: true

    

  end
  
  
  
  root "vibes#index"
end

app/models/dream.rb
class Dream < ApplicationRecord
  has_many :dreamcatchers
  has_many :dreamers, through: :dreamcatchers
  
  


  
end

app/models/dreamcatcher.rb
class Dreamcatcher < ApplicationRecord
  belongs_to :dream
  belongs_to :dreamer
  
end

app/models/dreamer.rb
class Dreamer < ApplicationRecord
  has_many :dreamcatchers
  has_many :dreams, through: :dreamcatchers
  accepts_nested_attributes_for :dreamcatcher
end

app/models/guide.rb
class Guide < ApplicationRecord
  has_many :lessons
  has_many :students, through: :lessons
end

app/models/image_element.rb
class ImageElement < ApplicationRecord
  belongs_to :user
 has_many :states, source: :vibes 
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :guide
  belongs_to :student
  
end

app/models/message.rb
class Message < ApplicationRecord
 
  belongs_to :user

  after_create_commit {
    MessageBroadcastJob.perform_later(self)
  }

  
end

app/models/oracle.rb
class Oracle < ApplicationRecord

  
  
  validates :wisdom, inclusion: { in: ['keep it a buck ','meh', 'try and relax', 'ugh', 'not in the mood', 'chill' ] }
  ORACLE_OPTIONS = [
    'keep it a buck',
     " meh ",
  "try and relax",
    'ugh',
    'not in the mood',
    'chill'
    

  ]

    
    def self.search(search)

      if search 
        find(:all, :conditions => [ Oracle::ORACLE_OPTIONS, {} ])
      else
        find(:all)
      end
    end
  
   




  

  def wisdom_bar
    return 'not-started' if wisdom.none?

    if wisdoms.all? { |oracle| wisdom.complete? }
      'complete'
    elsif wisdom.any? { |oracle| wisdom.in_progress? || wisdom.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def amount_done
    return 0 if wisdom.none?
    ((amount_done.to_f / all_oracles) * 100).round
  end

  def amount_done
    wisdom.select { |oracle| wisdom.complete? }.count
  end

  def all_oracles
    wisdoms.count
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :lessons
  has_many :guides, through: :lessons
  accepts_nested_attributes_for :lessons
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
         has_many :vibes,  dependent: :destroy
         has_many :messages, dependent: :destroy
         has_many :auras, :class_name => "Vibe", :foreign_key => "User_id", dependent: :destroy
         has_many :states, :class_name => "Vibe", :foreign_key => "User_id", dependent: :destroy
         has_many :details, :class_name => "Vibe", :foreign_key => "User_id", dependent: :destroy
        
         
         
        
        
         
         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
        end      
      end


      
         
    
    

     


  def self.search(search)
    
    if search
      User.where(' email LIKE :query', query: "%#{search}%")
     
    else
    unscoped
    end
  end
  
  
end
        
        
       
      
    

app/models/vibe.rb
class Vibe < ApplicationRecord
  belongs_to :user
  has_many :states 
  has_many :auras
  validates :state, inclusion: { in: ['whatevs', 'hurting', 'vibing', 'elevated', 'troubled', 'crazy', 'passionate' ] }
  has_one_attached :aura
  has_many_attached :files
  
 
  
  
  STATE_OPTIONS = [
    ['Whatevs', 'whatevs'],
    ['Hurting', 'hurting'],
    ['Vibing', 'vibing'],
    ['Elevated', 'elevated'],
    ['Troubled', 'troubled'],
    ['Crazy', 'crazy'],
    ['Passionate', 'passionate'],

  ]
   scope :hurting_vibe, -> { where("state > 2") }
 
  
         
      def color_aura
          case aura
          when 'hurting'
            'hurting'
          when 'whatevs'
            'whatevs'
          when 'vibing'
            'vibing'
          end
        end
          
          def color_state
            case state
            
            when 'hurting'
              'hurting'
            when 'whatevs'
              'whatevs'
            when 'vibing'
              'vibing'
            when 'elevated'
              'elevated'
            when 'troubled'
              'troubled'
            when 'crazy'
              'crazy'
            when 'passionate'
              'passionate'

            end
          end
end

app/controllers/vibes_controller.rb
class VibesController < ApplicationController
  before_action :find_vibe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :vibemeter]
  def index 
    if user_signed_in? 
		
			@vibes = Vibe.where(:user_id => current_user.id).order("created_at DESC")
      
      
      end
    end

     def vibemeter
      @vibes = Vibe.hurting_vibe
      end

    def new
      @vibe = current_user.vibes.build
    end

  def show 
    @vibe = Vibe.find(params[:id])
   
   end

  def create
    
    @vibe = current_user.vibes.build(vibe_params)
    if @vibe.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @vibe.update(vibe_params)
      redirect_to vibe_path(@vibe)
    else
      render 'new'
    end
  end
    
    def destroy
      @vibe.destroy
      redirect_to root_path
    end
  

  private 
  def vibe_params  
  params.require(:vibe).permit(:name, :details, :state, :aura, :file)
  end
  
  
  
  def find_vibe
    @vibe = Vibe.find(params[:id])
  end
end
 

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/enemies_helper.rb
module EnemiesHelper
end

app/helpers/grudges_helper.rb
module GrudgesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/oracle_helper.rb
module OracleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/helpers/vibe_helper.rb
module VibeHelper

  
   

end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/vibes/_aura.html.erb
<h1> My aura RN </h1>
<%= simple_form_for @vibe do |f| %>
 
<%= f.select :aura, Vibe::AURA_OPTIONS, {}, class: "form Control"%>

<%= f.button :submit %>

<% end %>

app/views/vibes/_form.html.erb
<h1> Create new Vibe </h1>
<%= simple_form_for @vibe do |f| %>
<%= f.input :name, label: "Name of vibe" %>
<%= f.input :details %>
<span class="badge bg-primary">Image/Aura</span>
<%= f.file_field :aura %>
<br>
<span class="badge bg-info text-dark">State Of Mind</span>
<%= f.select :state, Vibe::STATE_OPTIONS, {}, class: "form Control", label: "Name of vibe" %><br>

<br>
<input class="btn btn-primary" type="submit" value="Submit">

 <% end %>

app/views/vibes/_state.html.erb
<%= form_for @vibe do |f| %>
 <%= f.collection_check_boxes :options, [[true, 'Yes'] ,[false, 'No']], :first, :last %>
<% end %>

app/views/vibes/edit.html.erb
<div class="col-md-5 col-md-offset-3">
	<h1>Edit vibes</h1>

	<%= render 'form' %>
</div>

app/views/vibes/index.html.erb
  <div class="container-fluid">
     <center><p1>  V I B E S </p1> </center>
     </div>
  

      <% if user_signed_in? %>
          <div class= "center">
            <% @vibes.each do |vibe| %>
           
              <div class="jumbotron">
                <%=vibe.created_at.strftime("%b %d, %Y %l:%M %p")%>
                <h2> <%= link_to vibe.name, vibe %> </h2>
                    <p> <%= vibe.details %> </p>
                  <span class="badge rounded-pill bg-primary"><%= vibe.color_state %></span>
                    <br>
                    
                     <% if vibe.aura.attached? %>
                       <image src="<%=(url_for(vibe.aura)) %>" alt="profile pic" height="250", width="250"><br>
                      </div>  
                      <% end %>
                      </div>
                      
	                         
                      <% end %>

                    <br>
                     <% else %>
                     <% render 'layouts/static_landing_page' %>
  
                      <% end %>

        
                  
<%= link_to "New Vibe", new_vibe_path %>



 
               

app/views/vibes/show.html.erb
<div class="container-fluid">
  

<div class="jumbotron">
        <h4>My Vibe</h4> 
		<h2><%= @vibe.name %></h2>
		<h6> State Of Mind</h6> 
		<p><%= @vibe.state %><p>
		<h6> Details</h6> 
		<p><%= @vibe.details %><p>
   <% if @vibe.aura.attached? %>
	 <image src="<%=(url_for(@vibe.aura)) %>" alt="profile pic" height="250", width="250"><br>
	
                      
                      <%= video_tag(url_for(@vibe.file)) %>
   <% end %>
	 

		

		<%= link_to "Edit", edit_vibe_path(@vibe) %>
		<%= link_to "Delete", vibe_path(@vibe), method: :delete, data: { confirm: "Are you sure?" } %>
		<%= link_to "Back", root_path %>
   </div>
	</div>





	 
 

app/views/vibes/vibemeter.html.erb
<%= @vibes.each do |vibe| %> 

<% @vibes %>

<% end %>